# Generated by Django 4.0.2 on 2022-02-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='verification_type',
            field=models.CharField(choices=[('forget_password', 'forget_password'), ('email_verification', 'email_verification')], default='forget_password', max_length=250),
            preserve_default=False,
        ),
    ]
